import { useEffect, useState } from "react";
import { Link, NavLink, Navigate, Route, Routes, useNavigate, useParams, useSearchParams } from "react-router-dom";
import { MapContainer, Marker, Popup, TileLayer } from "react-leaflet";
import { Area, AreaChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { ArrowLeft, Check, CheckCircle2, ChevronRight, ClipboardList, Download, HandHeart, Info, Leaf, Loader2, LogIn, MapPin, PackageOpen, ShieldCheck, Sparkles, Store, Truck, UtensilsCrossed, XCircle, Zap } from "lucide-react";
import { api, apiConfigured } from "./lib/api";

const stages = ["draft","confirmed","matching","claimed","in_transit","delivered"];
const stageName = {draft:"Draft",confirmed:"Confirmed",matching:"Matching",claimed:"Claimed",in_transit:"In transit",delivered:"Delivered"};
const urgency = {high:"bg-red-50 text-red-700",medium:"bg-amber-50 text-amber-700",low:"bg-emerald-50 text-emerald-700"};
const get = (r) => r?.data?.data ?? r?.data ?? r;
const list = (x) => Array.isArray(x) ? x : x?.items || x?.data || [];
const date = (x) => x ? new Intl.DateTimeFormat("en-IN",{dateStyle:"medium",timeStyle:"short"}).format(new Date(x)) : "—";
const num = (x) => typeof x === "number" ? new Intl.NumberFormat("en-IN").format(x) : "—";

function useData(load,key) {
  const [s,set] = useState({loading:true,data:null,error:null,offline:false});
  const reload = async () => { set(x=>({...x,loading:true,error:null})); try { const r=await load(); set({loading:false,data:get(r),error:null,offline:!!r?.offline}); } catch(error) { set({loading:false,data:null,error,offline:false}); } };
  useEffect(()=>{reload();},[key]);
  return {...s,reload};
}

function Brand(){return <Link to="/login" className="inline-flex items-center gap-2 text-[#173f2e]"><span className="grid h-9 w-9 place-items-center rounded-md bg-[#173f2e] text-white"><Leaf className="h-5 w-5"/></span><b className="font-serif text-2xl">अन्नSetu</b></Link>}
function Load(){return <div className="grid min-h-[40vh] place-items-center"><Loader2 className="h-7 w-7 animate-spin text-[#173f2e]"/></div>}
function Empty({title="Nothing here yet",text,Icon=PackageOpen,offline,action}){return <div className="card grid min-h-52 place-items-center text-center"><div><Icon className="mx-auto mb-3 h-7 w-7 text-[#173f2e]"/><h3 className="text-xl">{title}</h3><p className="mt-2 max-w-sm text-sm text-[#667268]">{text}</p>{offline&&<p className="mt-2 text-xs text-[#8a948b]">Connect the backend API to load live data.</p>}{action&&<div className="mt-4">{action}</div>}</div></div>}
function ErrorBox({error,reload}){return <div className="card text-center"><h3 className="text-xl">Could not load this page</h3><p className="mt-2 text-sm text-red-700">{error?.message}</p><button className="btn-secondary mt-4" onClick={reload}>Try again</button></div>}
function Tip({children}){return <span className="group relative inline-flex"><Info className="h-3.5 w-3.5 text-[#7a857d]"/><span className="absolute bottom-5 left-1/2 z-20 hidden w-52 -translate-x-1/2 rounded bg-[#173f2e] p-2 text-center text-xs text-white group-hover:block">{children}</span></span>}

const nav=[["/kitchen/dashboard","Dashboard",Store],["/kitchen/report-surplus","Report surplus",ClipboardList],["/impact","Impact",Leaf],["/compliance","Compliance",PackageOpen]];
function Shell({title,subtitle,children,action}){return <div className="min-h-screen bg-[#f5f5ef]"><header className="border-b bg-[#f5f5ef]"><div className="mx-auto flex max-w-[650px] items-center justify-between px-4 py-4"><div><h1 className="text-[25px]">{title}</h1><p className="text-xs text-[#667268]">{subtitle}</p></div>{action}</div></header><main className="page">{children}</main><nav className="fixed bottom-0 left-0 right-0 z-20 flex justify-around border-t bg-white py-2">{nav.map(([to,name,Icon])=><NavLink key={to} to={to} className={({isActive})=>`flex flex-col items-center gap-1 text-[10px] ${isActive?"text-[#173f2e]":"text-[#7e887f]"}`}><Icon className="h-4 w-4"/>{name}</NavLink>)}</nav></div>}

const roles={kitchen:{name:"Kitchen",desc:"Institutional kitchen, canteen, or catering unit reporting surplus.",icon:Store,next:"/kitchen/dashboard"},recipient:{name:"Recipient org",desc:"NGO, shelter, food bank, or community kitchen receiving surplus.",icon:HandHeart,next:"/recipient/offers"},volunteer:{name:"Volunteer",desc:"Handles pickup and delivery between kitchens and recipients.",icon:Truck,next:"/volunteer/pickup/assigned"}};

function RolePicker(){return <main className="grid min-h-screen place-items-center bg-[#f5f5ef] p-4"><div className="w-full max-w-[405px]"><div className="mb-6 text-center">
  <Brand />
</div>

<img
  src="https://share.google/1xvhrALouBysM3j1s"
  alt="Food redistribution and community support"
  className="mb-5 h-44 w-full rounded-xl object-cover shadow-sm"
/><section className="card p-7"><h1 className="text-2xl">Who’s signing in?</h1><p className="mt-1 text-sm text-[#667268]">Pick the role this device will use.</p><div className="mt-5 space-y-2">{Object.entries(roles).map(([key,r])=>{const I=r.icon;return <Link key={key} to={`/login/${key}`} className="flex items-center gap-3 rounded-lg border p-3 hover:border-[#173f2e] hover:bg-[#eef3ec]"><span className="grid h-9 w-9 place-items-center rounded bg-[#e8eee5]"><I className="h-4 w-4"/></span><span className="flex-1"><b className="block text-sm">{r.name}</b><span className="block text-xs text-[#667268]">{r.desc}</span></span><ChevronRight className="h-4 w-4"/></Link>})}</div></section><p className="mt-4 text-center text-xs text-[#7a857d]">FSSAI-aligned surplus redistribution · built for institutional kitchens</p></div></main>}

function Login(){const {role}=useParams(),go=useNavigate(),r=roles[role]||roles.kitchen,[form,setForm]=useState({email:"",password:""}),[error,setError]=useState(""); const I=r.icon; async function submit(e){e.preventDefault();try{const res=await api.login({...form,role});if(res.offline)return go(r.next);const d=get(res);if(d?.accessToken)localStorage.setItem("annsetu_access_token",d.accessToken);go(r.next)}catch(x){setError(x.message)}} return <main className="grid min-h-screen place-items-center bg-[#f5f5ef] p-4"><div className="w-full max-w-[405px]"><div className="mb-8 text-center"><Brand/><label className="mt-7 block text-xs font-semibold">
  </div><form onSubmit={submit} className="card p-7"><Link to="/login" className="text-xs text-[#667268]">← Change role</Link><div className="mt-5 flex items-center gap-2"><I className="h-5 w-5"/><h1 className="text-2xl">Sign in as {r.name.toLowerCase()}</h1></div><p className="mt-1 text-sm text-[#667268]">{r.desc}</p><label className="mt-5 block text-xs font-semibold">Phone number or email<input required className="input" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></label><label className="mt-4 block text-xs font-semibold">Password<input required type="password" className="input" value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/></label>{error&&<p className="mt-3 text-xs text-red-700">{error}</p>}<button className="btn-primary mt-5 w-full">Sign in <ChevronRight className="h-4 w-4"/></button></form></div></main>}

function Dashboard(){const r=useData(api.kitchenDashboard,"dash"),go=useNavigate(),d=r.data||{},items=list(d.listings);return <Shell title={d.kitchenName||"Kitchen dashboard"} subtitle="Kitchen view" action={<button className="btn-primary bg-[#c9981e] text-[#173f2e] hover:bg-[#b88a18]" onClick={()=>go("/kitchen/report-surplus?urgent=1")}><Zap className="h-4 w-4"/>Urgent surplus</button>}>{r.loading?<Load/>:r.error?<ErrorBox {...r}/>:<><div className="space-y-3"><div className="card border-l-2 border-l-[#173f2e]"><h3>Tomorrow’s forecast</h3><p className="eyebrow">Predicted surplus load</p><p className="mt-2 font-serif text-3xl">{d.forecast?.headline||"Awaiting kitchen history"}</p></div><div className="card border-l-2 border-l-[#c9981e]"><h3>Surplus risk</h3><p className="mt-2 text-sm">{d.risk?.label||"Not calculated yet"}</p></div><div className="card border-l-2 border-l-[#173f2e]"><h3>Today’s AI brief</h3><p className="mt-2 text-sm">{d.brief||"Your one-line AI brief will appear when real kitchen data is connected."}</p></div></div><section className="card mt-4"><h3>7-day demand forecast</h3>{d.forecast?.points?.length?<div className="mt-4 h-48"><ResponsiveContainer><AreaChart data={d.forecast.points}><XAxis dataKey="label"/><YAxis/><Tooltip/><Area dataKey="value" stroke="#173f2e" fill="#dce8d8"/></AreaChart></ResponsiveContainer></div>:<p className="mt-4 text-sm text-[#667268]">Forecast chart will appear after backend data is available.</p>}</section><section className="card mt-4"><h3>Why this forecast</h3><p className="eyebrow">Plain-language reasoning</p>{d.forecast?.reasons?.length?<ul className="mt-3 space-y-2 text-sm">{d.forecast.reasons.map(x=><li key={x}>— {x}</li>)}</ul>:<p className="mt-3 text-sm text-[#667268]">Reasons will appear with real forecast data.</p>}</section><section className="card mt-4"><div className="flex justify-between"><div><h3>Active listings</h3><p className="eyebrow">Everything reported today, across every channel</p></div><Link className="btn-secondary px-3 py-2 text-xs" to="/kitchen/report-surplus">+ New listing</Link></div>{items.length?items.map(x=><Link key={x.id} to={`/kitchen/listings/${x.id}`} className="flex items-center justify-between border-b py-4 last:border-0"><span><b className="text-sm">{x.foodItem||x.title}</b><span className={`pill ml-2 ${urgency[x.urgency?.toLowerCase()]||urgency.low}`}>{x.urgency||"Low"} urgency</span><small className="mt-1 block text-xs text-[#667268]">{x.quantity} {x.unit} · pickup by {date(x.pickupBy)}</small></span><span className="text-xs">{stageName[x.status]||"Matching"} ›</span></Link>):<div className="mt-4"><Empty title="No listings yet" text="Report your first surplus to begin matching." offline={r.offline}/></div>}</section></>}</Shell>}
function Report(){
  const go=useNavigate(),[q]=useSearchParams(),urgent=q.get("urgent")==="1";
  const [f,setF]=useState({foodItem:"",quantity:"",unit:"kg",cookedAt:"",pickupBy:"",notes:"",urgency:urgent?"high":"medium"}),[msg,setMsg]=useState("");
  const u=(k,v)=>setF({...f,[k]:v});
  async function save(e){e.preventDefault();try{const r=await api.createListing({...f,quantity:Number(f.quantity)});if(r.offline)return setMsg("Backend is not connected yet. This form is ready for the real API.");go(`/kitchen/listings/${get(r).id}`)}catch(x){setMsg(x.message)}}
  return <Shell title="Report surplus" subtitle="These four fields are exactly what AI extracts from WhatsApp and calls."><form onSubmit={save} className="card mt-4 max-w-[460px] space-y-4"><label className="block text-xs font-semibold">Food item<input required className="input" placeholder="e.g. Vegetable pulao" value={f.foodItem} onChange={e=>u("foodItem",e.target.value)}/></label><div className="grid grid-cols-2 gap-3"><label className="text-xs font-semibold">Quantity<input required type="number" className="input" value={f.quantity} onChange={e=>u("quantity",e.target.value)}/></label><label className="text-xs font-semibold">Unit<select className="input" value={f.unit} onChange={e=>u("unit",e.target.value)}><option>kg</option><option>servings</option><option>packets</option><option>trays</option></select></label><label className="text-xs font-semibold">Cooked at<input required type="datetime-local" className="input" value={f.cookedAt} onChange={e=>u("cookedAt",e.target.value)}/></label><label className="text-xs font-semibold">Pickup by<input required type="datetime-local" className="input" value={f.pickupBy} onChange={e=>u("pickupBy",e.target.value)}/></label></div><label className="block text-xs font-semibold">Notes<textarea className="input" value={f.notes} onChange={e=>u("notes",e.target.value)}/></label><p className="rounded bg-[#eaf1e8] p-3 text-xs">This listing will look identical to one created by an AI phone call or WhatsApp message.</p>{msg&&<p className="text-xs text-red-700">{msg}</p>}<button className="btn-primary w-full">{urgent?"Start urgent matching":"Publish listing"}</button></form></Shell>
}

function Timeline({current}){const n=Math.max(0,stages.indexOf(current));return <div className="mt-5 grid gap-3 sm:grid-cols-6">{stages.map((x,i)=><div key={x} className="flex gap-2 sm:block"><b className={`grid h-7 w-7 place-items-center rounded-full text-xs ${i===n?"bg-[#173f2e] text-white":i<n?"bg-[#dce8d8]":"bg-[#ecece6]"}`}>{i<n?<Check className="h-4 w-4"/>:i+1}</b><span className={`text-xs ${i===n?"font-bold text-[#173f2e]":"text-[#667268]"}`}>{stageName[x]}</span></div>)}</div>}
function Map({pickup,recipient}){if(pickup?.latitude==null)return <Empty icon={MapPin} title="Map awaits a real location" text="Pickup and recipient pins appear when the backend sends coordinates."/>;let p=[pickup.latitude,pickup.longitude];return <MapContainer center={p} zoom={13}><TileLayer url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"/><Marker position={p}><Popup>{pickup.address}</Popup></Marker>{recipient?.latitude!=null&&<Marker position={[recipient.latitude,recipient.longitude]}><Popup>{recipient.address}</Popup></Marker>}</MapContainer>}
function Listing(){const {id}=useParams(),r=useData(()=>api.getListing(id),id),x=r.data,[msg,setMsg]=useState("");async function urgent(){const z=await api.urgentMatch(id);setMsg(z.offline?"Urgent matching will start when the API is connected.":"Live matching started.")}return <Shell title="Listing status" subtitle="Follow every handover"><>{r.loading?<Load/>:r.error?<ErrorState {...r}/>:!x?<Empty title="Listing unavailable" text="Create a surplus listing first."/>:<><div className="flex justify-between"><div><h2 className="page-title">{x.foodItem}</h2><p className="text-sm">{x.quantity} {x.unit} · pickup by {date(x.pickupBy)}</p></div><button className="btn-primary" onClick={urgent}><Zap className="h-4 w-4"/>Urgent</button></div>{msg&&<p className="mt-3 text-sm text-[#173f2e]">{msg}</p>}<section className="card mt-4"><h3>Handover progress</h3><Timeline current={x.status}/></section><section className="card mt-4 h-72 p-2"><Map pickup={x.pickup} recipient={x.recipient}/></section></>}</></Shell>}

function Offers(){const r=useData(api.recipientOffers,"offers"),items=list(r.data),[m,setM]=useState("");async function act(id,d){const z=await api.respondToOffer(id,d);setM(z.offline?"Action ready for backend.":`Offer ${d}d.`)}return <Shell title="Incoming offers" subtitle="Surplus food near you, matched in real time.">{r.loading?<Load/>:r.error?<ErrorState {...r}/>:!items.length?<Empty icon={HandHeart} title="No offers right now" text="New nearby offers will appear here." offline={r.offline}/>:<>{m&&<p className="mb-3 text-sm">{m}</p>}{items.map(x=><article key={x.id} className="card mb-3"><div className="flex justify-between"><b>{x.foodItem||x.title}</b><span className="pill bg-[#eaf1e8]">{x.distanceKm||"—"} km</span></div><p className="mt-1 text-xs text-[#667268]">{x.kitchen?.name} · {x.quantity} {x.unit} · pickup by {date(x.pickupBy)}</p><div className="mt-4 grid grid-cols-2 gap-2"><button className="btn-secondary text-red-700" onClick={()=>act(x.id,"decline")}>Decline</button><button className="btn-primary" onClick={()=>act(x.id,"accept")}>Accept</button></div></article>)}</>}</Shell>}

function Pickup(){const {id}=useParams(),r=useData(()=>api.getPickup(id),id),x=r.data,[otp,setOtp]=useState(""),[m,setM]=useState("");async function done(e){e.preventDefault();const z=await api.verifyDelivery(id,otp);setM(z.offline?"OTP will verify with the backend.":"Delivery verified.")}return <Shell title="Your pickup" subtitle={x?.reference||"Assigned pickup"}>{r.loading?<Load/>:!x?<Empty icon={Truck} title="No pickup assigned yet" text="Your assigned delivery will appear here." offline={r.offline}/>:<><section className="card h-72 p-2"><Map pickup={x.pickup} recipient={x.recipient}/></section><section className="card mt-3"><h3>Load</h3><p className="mt-2 text-sm">{x.foodItem} · {x.quantity} {x.unit}</p></section><form onSubmit={done} className="card mt-3"><h3>Confirm handover</h3><p className="text-xs text-[#667268]">Ask the recipient to read their 4-digit code.</p><input required maxLength="4" inputMode="numeric" className="input text-center text-2xl tracking-[1em]" value={otp} onChange={e=>setOtp(e.target.value.replace(/\D/g,"").slice(0,4))}/>{m&&<p className="mt-2 text-xs">{m}</p>}<button className="btn-primary mt-4 w-full">Verify delivery</button></form></>}</Shell>}

function Impact(){const r=useData(api.impact,"impact"),d=r.data||{},trend=d.trend||[],box=(n,v,t)=><div className="card border-l-2 border-l-[#173f2e]"><p className="flex gap-1 text-xs">{n}<Tip>{t}</Tip></p><p className="mt-2 font-serif text-3xl">{v}</p></div>;return <Shell title="Impact" subtitle="Every figure links to how it is calculated.">{r.loading?<Load/>:r.error?<ErrorState {...r}/>:<><div className="grid grid-cols-2 gap-3">{box("Meals redistributed",num(d.mealsRedistributed),d.computations?.mealsRedistributed||"Verified delivered quantities divided by serving size.")}{box("Waste prevented",d.wastePreventedKg!=null?`${num(d.wastePreventedKg)} kg`:"—",d.computations?.wastePreventedKg||"Weight of verified deliveries.")}{box("Rupees saved",d.rupeesSaved!=null?`₹${num(d.rupeesSaved)}`:"—",d.computations?.rupeesSaved||"Replacement meal cost estimate.")}</div><section className="card mt-4"><h3>Meals redistributed — trend</h3>{trend.length?<div className="h-56"><ResponsiveContainer><AreaChart data={trend}><XAxis dataKey="label"/><YAxis/><Tooltip/><Area dataKey="value" stroke="#8d670e" fill="#f2dfac"/></AreaChart></ResponsiveContainer></div>:<Empty title="Trend awaits verified deliveries" text="The chart will only use real completed handovers." offline={r.offline}/>}</section></>}</Shell>}

function Compliance(){const r=useData(api.compliance,"comp"),rows=list(r.data);return <Shell title="Compliance register" subtitle="FSSAI surplus-food handover log — every row is OTP-verified." action={<div className="flex gap-2"><button className="btn-secondary text-xs" disabled={!apiConfigured} onClick={()=>window.open(api.exportRegister("csv"))}><Download className="h-3 w-3"/>CSV</button><button className="btn-secondary text-xs" disabled={!apiConfigured} onClick={()=>window.open(api.exportRegister("pdf"))}>PDF</button></div>}>{r.loading?<Load/>:!rows.length?<Empty icon={ShieldCheck} title="No completed handovers yet" text="Verified deliveries will appear in this register." offline={r.offline}/>:<div className="card overflow-x-auto p-0"><table className="w-full min-w-[650px] text-left text-xs"><thead className="bg-[#eeeeE6]"><tr>{["ID","Date","Kitchen","Recipient","Item","Qty"].map(x=><th key={x} className="p-3">{x}</th>)}</tr></thead><tbody>{rows.map(x=><tr key={x.id} className="border-t"><td className="p-3">{x.reference||x.id}</td><td className="p-3">{date(x.deliveredAt)}</td><td className="p-3">{x.kitchen?.name||x.kitchenName}</td><td className="p-3">{x.recipient?.name||x.recipientName}</td><td className="p-3">{x.foodItem}</td><td className="p-3">{x.quantity} {x.unit}</td></tr>)}</tbody></table></div>}</Shell>}

export default function App(){return <Routes><Route path="/login" element={<RolePicker/>}/><Route path="/login/:role" element={<Login/>}/><Route path="/kitchen/dashboard" element={<Dashboard/>}/><Route path="/kitchen/report-surplus" element={<Report/>}/><Route path="/kitchen/listings/:id" element={<Listing/>}/><Route path="/recipient/offers" element={<Offers/>}/><Route path="/volunteer/pickup/:id" element={<Pickup/>}/><Route path="/impact" element={<Impact/>}/><Route path="/compliance" element={<Compliance/>}/><Route path="/" element={<Navigate to="/login"/>}/></Routes>}
